### ISSUE TITLE
Feture request - resume at last frame, start at a specified frame

### ISSUE THREAD

**Issue by simonjowett** [szantaii/slow-movie-frame-10.3#3]
This is a feature request to *resume the playback at the last frame (prior to shutdown or service stop).   In addition, for those movies with a long intro (black screen for a few minutes at the start of 2001 A Space Odyssey)! can a 'start at frame'  be specified?

*EDIT - it does resume I double checked and found it works - sorry!

**Comment by szantaii** [comment]
As you have mentioned the playback is resumed from the last frame when restarting the `slow-movie-player.service` or powering off and on the device.

I do not intend to implement a start frame option because intros vary from video to video.

However, you can manually adjust the `next_frame` and `next_timestamp` fields of each video in the JSON file I mentioned in https://github.com/szantaii/slow-movie-frame-10.3/issues/2#issuecomment-1538965705. Just make sure that you calculate the proper frame from the timestamp and vice versa. (E.g. you want to skip 90 seconds of your 29.97 fps video, then you have to set the `next_timestamp` value to `90000` and the `next_frame` value to `2697` (because 90 seconds times 29.97 frames per second will result in 2697.3).)

Make sure to stop the `slow-movie-player.serice` (`sudo systemctl stop slow-movie-player.service`) before adjusting your JSON file and start the service afterwards (`sudo systemctl start slow-movie-player.service`).
